name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build plugin
      run: dotnet build --configuration Release

    - name: Create ZIP archive
      run: |
        mkdir -p dist
        dotnet publish -c Release -o dist
        cd dist && zip -r ../VibeYourMaid.zip *

    - name: Upload ZIP archive
      uses: actions/upload-artifact@v2
      with:
        name: VibeYourMaid
        path: VibeYourMaid.zip
