name: Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: '5.x'

      - name: Restore NuGet Packages
        run: nuget restore COM3D2.VibeYourMaid.Plugin.sln

      - name: Build Solution
        run: |
          msbuild COM3D2.VibeYourMaid.Plugin.sln /p:Configuration=COM3D2-Release /p:Platform="Any CPU"

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: COM3D2.HighHeel.Plugin
          path: COM3D2.VibeYourMaid.Plugin/bin/Release/COM3D2/COM3D2.VibeYourMaid.Plugin.dll
